<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>3 Tools | Computational Film Analysis with R</title>
<meta name="author" content="Nick Redfern">
<meta name="description" content="This chapter presents a brief overview of the three tools we will use to analyse films computationally – R, RStudio, and FFmpeg. This chapter is intended only to provide enough knowledge about...">
<meta name="generator" content="bookdown 0.26 with bs4_book()">
<meta property="og:title" content="3 Tools | Computational Film Analysis with R">
<meta property="og:type" content="book">
<meta property="og:image" content="/images/cover.png">
<meta property="og:description" content="This chapter presents a brief overview of the three tools we will use to analyse films computationally – R, RStudio, and FFmpeg. This chapter is intended only to provide enough knowledge about...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="3 Tools | Computational Film Analysis with R">
<meta name="twitter:description" content="This chapter presents a brief overview of the three tools we will use to analyse films computationally – R, RStudio, and FFmpeg. This chapter is intended only to provide enough knowledge about...">
<meta name="twitter:image" content="/images/cover.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1/transition.js"></script><script src="libs/bs3compat-0.3.1/tabs.js"></script><script src="libs/bs3compat-0.3.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script><link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="libs/datatables-binding-0.23/datatables.js"></script><link href="libs/dt-core-1.11.3/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="libs/dt-core-1.11.3/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="libs/dt-core-1.11.3/js/jquery.dataTables.min.js"></script><link href="libs/dt-ext-fixedcolumns-1.11.3/css/fixedColumns.dataTables.min.css" rel="stylesheet">
<script src="libs/dt-ext-fixedcolumns-1.11.3/js/dataTables.fixedColumns.min.js"></script><link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script><script src="libs/plotly-binding-4.10.0/plotly.js"></script><script src="libs/typedarray-0.1/typedarray.min.js"></script><link href="libs/plotly-htmlwidgets-css-2.5.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="libs/plotly-main-2.5.1/plotly-latest.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
          margin-bottom: 2em;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="cfa_book.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Computational Film Analysis with R</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Welcome</a></li>
<li><a class="" href="preface.html"><span class="header-section-number">1</span> Preface</a></li>
<li><a class="" href="CFA.html"><span class="header-section-number">2</span> Computational film analysis</a></li>
<li><a class="active" href="tools.html"><span class="header-section-number">3</span> Tools</a></li>
<li><a class="" href="audio.html"><span class="header-section-number">4</span> Analysing film audio</a></li>
<li><a class="" href="colour.html"><span class="header-section-number">5</span> Analysing film colour</a></li>
<li><a class="" href="editingI.html"><span class="header-section-number">6</span> Analysing film editing I</a></li>
<li><a class="" href="editingII.html"><span class="header-section-number">7</span> Analysing film editing II</a></li>
<li><a class="" href="categorical.html"><span class="header-section-number">8</span> Analysing shot data</a></li>
<li><a class="" href="texts.html"><span class="header-section-number">9</span> Analysing lexical texts</a></li>
<li><a class="" href="references.html"><span class="header-section-number">10</span> References</a></li>
<li class="book-part">Appendix</li>
<li><a class="" href="colophon.html">Colophon</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/DrNickRedfern/CFA-with-R">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><!-- Modal --><div id="myModal" class="modal">
   <img class="modal-content" id="img01"><div id="caption"></div>
</div>
<div id="tools" class="section level1" number="3">
<h1>
<span class="header-section-number">3</span> Tools<a class="anchor" aria-label="anchor" href="#tools"><i class="fas fa-link"></i></a>
</h1>
<p><br>
This chapter presents a brief overview of the three tools we will use to analyse films computationally – R, RStudio, and FFmpeg. This chapter is intended only to provide enough knowledge about these tools so that when we come to apply them in subsequent chapters we can focus on analysing films and learning key methods in an applicable framework rather than overloading the reader with information without context.</p>
<p>There are numerous other excellent guides to using these technologies that provide comprehensive tuition for the reader who wants to delve deeper. The website <a href="http://www.r%E2%80%91tutor.com">R Tutorial</a> is a good place to start if you have never used R before, and <a href="https://www.r-bloggers.com">R-Bloggers</a> has excellent bite size tutorials. Hadley Wickham and Garrett Grolemund’s <em>R for Data Science</em> <span class="citation">(<a href="references.html#ref-wickham2017r4ds" role="doc-biblioref">Wickham &amp; Grolemund, 2017</a>)</span> provides a comprehensive overview of the <code>tidyverse</code> suite of packages (of which we will make extensive use in this book) and good practice when using R; it can be accessed online at <a href="https://r4ds.had.co.nz">https://r4ds.had.co.nz</a>.</p>
<div id="r" class="section level2" number="3.1">
<h2>
<span class="header-section-number">3.1</span> R<a class="anchor" aria-label="anchor" href="#r"><i class="fas fa-link"></i></a>
</h2>
<p><a href="https://www.r-project.org">R</a> is a free and open-source environment for statistical computing and graphics and a programming language available for Windows, Linux, and MacOS.</p>
<p>R was created for statistical computing and data analysis by statisticians and data analysts and is the principal software used in many areas of data science and academia. It was not designed for software development. Consequently, R’s underlying logic is that of the statistician and the data analyst rather than the software developer. Using R, I find that I spend less time writing code to analyse data and more time thinking about the question I am trying to answer because it better fits my analytical workflow compared to using other tools that were designed as a programming language (such as <a href="https://www.python.org">Python</a> or <a href="https://julialang.org">Julia</a>) and which have a different underlying logic. (I’m sure that those whose background is in programming rather than data science would prefer to use Python rather than R for the same reasons). This does not mean that R is the only tool suitable for computational film analysis, and there are some areas where other tools are optimal due to their availability and their broad support base. For example, Python is the preferred language for computer vision and machine learning tasks, both of which are relevant to computational film analysis. Part of designing a computational film analysis project is to choose how the methods employed will be computationally operationalised. The choice of analytical tool depends on the researcher, their project goals, and how they like to work.</p>
<p>There are several reasons why R is a desirable choice. R is <em>freely available</em> across a range of platforms, making it easy to share code and replicate research without worrying about licenses or replicating workflows based on point-and-click selections from menus. R is <em>highly extensible</em> with thousands of packages. R is <em>flexible</em>, and can be used for data visualisation, exploratory data analysis, and statistical modelling; data mining and machine learning; web scraping; and to create and publish documents (such as handouts, articles, or books – including this one), interactive notebooks, websites, and applications. The extensibility and flexibility of R mean that it is often the only tool required at each stage of our workflow, including data cleaning and analysis, producing publication-quality visualisations, and creating research outputs, thereby greatly simplifying the management of a research project. Learning to analyse data by writing code forces the researcher to think more deeply about what they want to do and how they will achieve their goals than software that requires them only to point-and-click an item from a menu. Consequently, learning to use R results in <em>a greater knowledge</em> gain of both quantitative methods and using data analysis tools. It will also enable you to learn more about the data you have and what it can tell you about the world. Finally, the ability to share the R code used in a research project promotes <em>reproducibility</em> and <em>accountability</em> in research, allowing other researchers to understand how an analyst arrived at the conclusions of their CFA project and to reproduce the analysis.</p>
<div id="installing-r" class="section level3" number="3.1.1">
<h3>
<span class="header-section-number">3.1.1</span> Installing R<a class="anchor" aria-label="anchor" href="#installing-r"><i class="fas fa-link"></i></a>
</h3>
<p>R can be downloaded from the Comprehensive R Archive Network (CRAN) at <a href="https://cran.r%E2%80%91project.org">https://cran.r‑project.org</a>. The installation process varies from platform to platform (Windows, Linux, and MacOS) but is in no case difficult and the CRAN website has clear instructions for all operating systems. Once the installation process is completed you will have the R scripting language, the R environment and console (Figure <a href="tools.html#fig:tools-R-image-env">3.1</a>), and the base set of data analysis packages ready for use.</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:tools-R-image-env"></span>
<img src="Images/tools-R-image-env.png" alt="The R environment and console. Code is entered at the command prompt `&gt;`. ☝️" width="90%" class="zooom"><p class="caption">
Figure 3.1: The R environment and console. Code is entered at the command prompt <code>&gt;</code>. ☝️
</p>
</div>
</div>
<div id="using-r" class="section level3" number="3.1.2">
<h3>
<span class="header-section-number">3.1.2</span> Using R<a class="anchor" aria-label="anchor" href="#using-r"><i class="fas fa-link"></i></a>
</h3>
<p>In this section, I cover some basic concepts required to make sense of code written in R. Other key concepts (such as control flow, vectorisation, and accessing elements) will be introduced in the contexts in which they are applied to make their meaning and use clear.</p>
<p>R can be used simply as a calculator to perform mathematical operations, entering values at the command prompt (<code>&gt;</code>) in the console, and pressing <kbd>Enter</kbd>.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">2</span> <span class="op">+</span> <span class="fl">3</span></code></pre></div>
<pre><code>## [1] 5</code></pre>
<p>In the above case, R prints the answer but does not store the result for later use. To store the answer, we need to assign the output of a command to an object using the <em>assignment operator</em> <code>&lt;-</code>, which combines a less than sign (<code>&lt;</code>) with a dash (<code>-</code>) and is used to name objects, assign values to variables, to evaluate expressions, or apply functions and pass the value to an object.</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Store the result of a sum in the variable answer</span>
<span class="va">answer</span> <span class="op">&lt;-</span> <span class="fl">2</span> <span class="op">+</span> <span class="fl">5</span>

<span class="co"># Call the variable by typing the name of the object</span>
<span class="va">answer</span></code></pre></div>
<pre><code>## [1] 7</code></pre>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Use the object answer for another sum</span>
<span class="va">answer</span> <span class="op">+</span> <span class="fl">5</span></code></pre></div>
<pre><code>## [1] 12</code></pre>
<p>The <em>names</em> of objects are case‑sensitive: for example, the objects <code>answer</code> and <code>ANSWER</code> are different objects. Names can contain letters, numbers, underscores, and periods, but should start with a letter. (Names can start with a period followed by a letter, but this is to be avoided in general). Names cannot start with a number or an underscore. Names assigned to objects can be formed in several ways:</p>
<ul>
<li>all one word in lowercase: <code>objectname</code>
</li>
<li>separating words with a period: <code>object.name</code>
</li>
<li>separating words with an underscore: <code>object_name</code>
</li>
<li>
<a href="https://en.wikipedia.org/wiki/Camel_case">camel case</a> beginning with lower case: <code>objectName</code>
</li>
<li>camel case beginning with upper case: <code>ObjectName</code>
</li>
</ul>
<p>There is no right or wrong choice, but <em>consistency is a source of sanity when coding</em>. I prefer using the underscore method because names written using this format are easier to read. Finally, names cannot use any of the <a href="https://www.datamentor.io/r-programming/reserved-words/">reserved words</a> used by R (e.g., <code>TRUE</code>, <code>FALSE</code>, <code>NULL</code>, etc.).</p>
<p><em>Objects</em> in R include <a href="https://data-flair.training/blogs/data-structures-in-r/">data structures</a> (such as lists, vectors, matrices, data frames, etc.), variables, functions, and packages. The <a href="https://www.statmethods.net/interface/workspace.html">workspace</a> comprises the collection of objects currently active in an R session. The workspace and the objects it contains will be permanently lost when a session is closed unless saved as a <code>.RData</code> file. We can save either the whole workspace or individual objects in the workspace.</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Save the workspace and the objects it contains</span>
<span class="fu"><a href="https://rdrr.io/r/base/save.html">save.image</a></span><span class="op">(</span><span class="st">"TodaysWork.RData"</span><span class="op">)</span>

<span class="co"># Save the object answer in a .RData file</span>
<span class="fu"><a href="https://rdrr.io/r/base/save.html">save</a></span><span class="op">(</span><span class="va">answer</span>, file <span class="op">=</span> <span class="st">"answer.RData"</span><span class="op">)</span> </code></pre></div>
<p>To restore a workspace and/or objects to an active R session, use the <code><a href="https://rdrr.io/r/base/load.html">load()</a></code> function.</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Load saved objects into an R session</span>
<span class="fu"><a href="https://rdrr.io/r/base/load.html">load</a></span><span class="op">(</span><span class="st">"answer.RData"</span><span class="op">)</span></code></pre></div>
</div>
<div id="comments" class="section level3" number="3.1.3">
<h3>
<span class="header-section-number">3.1.3</span> Comments<a class="anchor" aria-label="anchor" href="#comments"><i class="fas fa-link"></i></a>
</h3>
<p>In R, <em>comments</em> are human readable descriptions of the purpose of a piece of code and begin with a hashmark (<code>#</code>). Anything after <code>#</code> on a line of code is not run.</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Comments can be on a single line</span>
<span class="co"># or multiple lines</span>
<span class="va">answer</span> <span class="op">&lt;-</span> <span class="fl">2</span> <span class="op">+</span> <span class="fl">5</span>  <span class="co"># Inline comments can also be added to a line of code</span></code></pre></div>
<p>Comments do not excuse poorly written code and meaningful names should be used whenever possible; but they are essential to producing good code:</p>
<ul>
<li>Comments make code <em>navigable</em>: a long script is easy to use if you can find your way around it and comments make valuable signposts.</li>
<li>Comments make code <em>shareable</em>: someone else should be able to understand the code you have written without having to decipher the code itself.</li>
<li>Comments make code <em>maintainable</em>: the ability to re-use code over time depends on your ability to understand what you were thinking when you originally wrote that code because you <em>will</em> forget.</li>
</ul>
<p><em>Header comments</em> at the top of a script should describe who wrote the code, why it was written, and what it should do. Functions should be commented to describe their purpose and parameters. Inline comments should be used to make what a piece of code does obvious if it is not already – comments do not need to duplicate code.</p>
</div>
<div id="functions" class="section level3" number="3.1.4">
<h3>
<span class="header-section-number">3.1.4</span> Functions<a class="anchor" aria-label="anchor" href="#functions"><i class="fas fa-link"></i></a>
</h3>
<p>A <em>function</em> is a self-contained piece of code that performs a defined task, taking some sort of data as an input, processing it, and returning a result (such as a model, a plot, or a data structure).</p>
<p>Functions take the form of the function name followed by parentheses: <code>function_name()</code>. The input(s) to a function are its <em>arguments</em>, and includes</p>
<ul>
<li>the data we wish to apply the function to; and</li>
<li>any control parameters that determine how the function behaves (e.g., should the function return a plot or not).</li>
</ul>
<p>Arguments are optional and some functions may have no arguments: for example, to get the current working directory we do not need to add any arguments to the call <code><a href="https://rdrr.io/r/base/getwd.html">getwd()</a></code>, but we do need the parentheses. Arguments may have <em>default</em> values that will be used if we do not explicitly specify that argument: for example, a function that returns a plot may have the default argument <code>plot = TRUE</code> and will automatically return a plot by default unless we set <code>plot = FALSE</code>. To get a list of the arguments for a function we can use <code>args(function_name)</code>.</p>
<p>Part of the flexibility of R is that it allows users to create their own functions as objects in the workspace using the <code>function()</code> function. All functions have the same basic form, comprising a function name, a set of arguments, and a function body.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="tools.html#cb10-1" aria-hidden="true" tabindex="-1"></a>function_name <span class="ot">&lt;-</span> <span class="cf">function</span>(arg_1, arg_2, …){</span>
<span id="cb10-2"><a href="tools.html#cb10-2" aria-hidden="true" tabindex="-1"></a>    function_statements</span>
<span id="cb10-3"><a href="tools.html#cb10-3" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>As an object in the workspace a function should have a name that is short but informative – we should have a sense of what a function does from its name. As noted above, arguments are the inputs of a function to which we want to apply operations. Those operations are implemented in the function statements wrapped by the curly braces. For example, to create a function to add two numbers together and return their sum, we create a function named <code>addition()</code> that takes two arguments (a and b) and adds them together.</p>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># A simple function to add two numbers together</span>
<span class="va">addition</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">a</span>, <span class="va">b</span><span class="op">)</span><span class="op">{</span>
    <span class="va">a</span> <span class="op">+</span> <span class="va">b</span>
<span class="op">}</span>

<span class="co"># Use addition() to add 2 and 3</span>
<span class="fu">addition</span><span class="op">(</span><span class="fl">2</span>, <span class="fl">3</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 5</code></pre>
<p>Functions can take other functions as their arguments and can be nested: for example, <code>addition(addition(2, 3), addition(4,2))</code> is a perfectly valid (if ugly) application of the above <code>addition()</code> function and will return the correct result of <code>11</code>.</p>
<p>If you find yourself repeatedly using the same piece of code in a project or across a set of projects it makes sense to put it into a function and then call that function when needed rather than clutter your project through repetition. Functions can be stored in files with the extension <code>.R</code>: for example, we could save the <code>addition()</code> function in the file <code>addition.R</code>. This creates a script file that can be loaded whenever we wish to apply the function, making code <em>reusable</em> across projects, <em>shareable</em> with other users, and <em>easier to maintain</em> because you only need to manage one chunk of code rather than several instances of the same code in a project. The <code><a href="https://rdrr.io/r/base/source.html">source()</a></code> function loads the functions stored in a <code>.R</code> script into the workspace.</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/source.html">source</a></span><span class="op">(</span><span class="st">"addition.R"</span><span class="op">)</span></code></pre></div>
<p>A script may contain multiple functions, <em>all</em> of which will be called into the workspace when the file is sourced. However, as scripts containing multiple functions become larger and more complicated it is preferable to have a single script for each function and to store and use those functions as a package.</p>
</div>
<div id="packages" class="section level3" number="3.1.5">
<h3>
<span class="header-section-number">3.1.5</span> Packages<a class="anchor" aria-label="anchor" href="#packages"><i class="fas fa-link"></i></a>
</h3>
<p><em>Packages</em> comprise sets of functions, data, and documentation that extend the functionality of R. R has an enormous collection of libraries (18000+) covering an enormous range of functions. If an analytical method for your data exists, then there is at least one R package for applying that method. Packages are stored in online repositories and can be downloaded and installed directly within R. The Comprehensive R Archive Network (CRAN) is the official repository for R packages and publishes packages that meet its policies for package development, but packages (and individual functions) can also be accessed from GitHub (NB: this requires the devtools or pacman packages).</p>
<p>A package’s functions are only available to use if the required package is installed on a computer and the package has been loaded into the current workspace. We can check which packages are currently loaded into an R session using <code><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo()</a></code>, which will print out information about R, the operating system, and any packages loaded in the workspace. Loading a package means that every function in that package is available in the namespace. If we want to use an individual function without loading the whole package, we can call the function as <code>package_name::function_name()</code> if the package is installed on a computer.</p>
<p>Packages and functions are objects in the workspace and so their names are case‑sensitive: for example, <code>tuner::readwave()</code> will <em>not</em> load a wave file into R because the names of the package and the function are <code><a href="https://rdrr.io/pkg/tuneR/man/readWave.html">tuneR::readWave()</a></code>.</p>
<div id="pacman" class="section level4" number="3.1.5.1">
<h4>
<span class="header-section-number">3.1.5.1</span> pacman<a class="anchor" aria-label="anchor" href="#pacman"><i class="fas fa-link"></i></a>
</h4>
<p>The <a href="http://trinker.github.io/pacman/vignettes/Introduction_to_pacman.html">pacman</a> package is an R package management tool comprising a useful set of functions to streamline the process of install packages and loading them into the workspace. To install pacman we use the base <code><a href="https://rdrr.io/r/utils/install.packages.html">install.packages()</a></code> command.</p>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Note the quote marks around the package name</span>
<span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span> </code></pre></div>
<p>Using the <code><a href="https://rdrr.io/pkg/pacman/man/p_load.html">pacman::p_load()</a></code> function, it is now possible to load multiple packages with a single command, separating the package names with commas. To install but <em>not</em> load a package, we use <code><a href="https://rdrr.io/pkg/pacman/man/p_install.html">pacman::p_install()</a></code>. For example, to load the tuneR and seewave packages we will use in Chapter <a href="audio.html#audio">4</a> we use the following code:</p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Quote marks are not needed using p_load()</span>
<span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">tuner</span>, <span class="va">seewave</span><span class="op">)</span></code></pre></div>
<p><code><a href="https://rdrr.io/pkg/pacman/man/p_load.html">pacman::p_load()</a></code> will automatically install any packages not already installed on your computer (NB: an internet connection is required). Packages can be unloaded once they are no longer needed using <code><a href="https://rdrr.io/pkg/pacman/man/p_unload.html">pacman::p_unload()</a></code> and can be updated using <code><a href="https://rdrr.io/pkg/pacman/man/p_update.html">pacman::p_update()</a></code>.</p>
</div>
<div id="tidyverse" class="section level4" number="3.1.5.2">
<h4>
<span class="header-section-number">3.1.5.2</span> tidyverse<a class="anchor" aria-label="anchor" href="#tidyverse"><i class="fas fa-link"></i></a>
</h4>
<p>The most common call we will make using pacman is to load the <a href="https://www.tidyverse.org">tidyverse</a> package (<span class="citation">Wickham et al. (<a href="references.html#ref-wickham2019wttt" role="doc-biblioref">2019</a>)</span>).</p>
<p>The tidyverse package is not really a package; it suite of packages for data science that share a common approach to processing and visualising data, and which are designed to have a single workflow that streamlines the analytical process. Almost all the general tasks of data analysis – data inspection and summarisation, <a href="https://en.wikipedia.org/wiki/Data_wrangling">data wrangling</a>, <a href="https://en.wikipedia.org/wiki/Data_cleansing">data cleaning</a>, and <a href="https://en.wikipedia.org/wiki/Data_and_information_visualization">data visualisation</a> – can be done using the tidyverse suite.</p>
<p>Installing the tidyverse package will install the following individual packages:</p>
<ul>
<li>
<a href="https://readr.tidyverse.org">readr</a>: read and parse data files (<code>.csv</code>, <code>.tsv</code>) into R’s workspace. Loading a file using <code><a href="https://readr.tidyverse.org/reference/read_delim.html">readr::read_csv()</a></code> will automatically load the data into a data frame (see <a href="tools.html#df">below</a>). To read Excel files use the <a href="https://readxl.tidyverse.org">readxl</a> package. To work with googlesheets use <a href="https://googlesheets4.tidyverse.org">googlesheets4</a>.</li>
<li>
<a href="https://dplyr.tidyverse.org">dplyr</a>: manipulate data in tabular format. The functions <code>select()</code>, <code><a href="https://rdrr.io/r/stats/filter.html">filter()</a></code>, <code>arrange()</code>, <code>mutate()</code>, <code>summarise()</code>, and <code><a href="https://rdrr.io/r/grDevices/plotmath.html">group()</a></code> are the ones you will use most when analysing data.</li>
<li>
<a href="https://tidyr.tidyverse.org">tidyr</a>: reshape and tidy data frames based on the concept of <em>tidy data</em>.</li>
<li>
<a href="https://stringr.tidyverse.org">stringr</a>: work with strings (text data).</li>
<li>
<a href="https://forcats.tidyverse.org">forcats</a>: work with categorical data as factors.</li>
<li>
<a href="https://tibble.tidyverse.org">tibble</a>: an alternative to the data frame data structure in R.</li>
<li>
<a href="https://purrr.tidyverse.org">purrr</a>: apply functions to data frames.</li>
<li>
<a href="https://ggplot2.tidyverse.org">ggplot2</a>: plot your data and customize just about any aspect of a plot you can think of. There are numerous extensions that add functionality to ggplot2 while maintaining a consistent aesthetic across visualisations.</li>
</ul>
<p>The tidyverse has a selection of <a href="https://www.rstudio.com/resources/cheatsheets/">cheat sheets</a> to help you use the packages efficiently.</p>
<p>Loading the tidyverse package will load all the packages in the suite, though each package in the suite can be loaded individually if desired. For example, if you have already prepared your data and want to create a plot then you can load just the ggplot2 package by calling that package only.</p>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Load the full suite of packages in the tidyverse</span>
<span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">tidyverse</span><span class="op">)</span>

<span class="co"># Load ggplot2 only</span>
<span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">ggplot2</span><span class="op">)</span></code></pre></div>
<p>A key concept underpinning the tidyverse is <em>tidy data</em> <span class="citation">(<a href="references.html#ref-wickham2014tdxx" role="doc-biblioref">Wickham, 2014</a>)</span>. In tidy data</p>
<ul>
<li>every column is variable.</li>
<li>every row is an observation.</li>
<li>every cell is a single value.</li>
</ul>
<p>For example, when we come to analyse colour in Chapter <a href="colour.html#colour">5</a> we will calculate the average colour of a frame of a short film. This data will be stored in a data frame in which will be store the following information in the tidy data format:</p>
<ul>
<li>each column is a variable in the data set that identifies the frame (<code>frame number</code>, <code>frame_id</code>), the time at which the frame occurs in the film (<code>time</code>), and the colour parameters of a frame in a colour space (<code>L</code>, <code>A</code>, <code>B</code>, <code>C</code>, <code>H</code>, <code>S</code>, <code>r</code>, <code>g</code>, <code>b</code>).</li>
<li>the observational unit of the data is a frame and each row represents a frame from the film.</li>
<li>each cell is the value of a variable for a frame.</li>
</ul>
<p>Table <a href="tools.html#tab:tools-tidyverse-table-tidy">3.1</a> illustrates the arrangement of this data in tidy data format.</p>
<div id="htmlwidget-e90f89edbd1fad068520" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-e90f89edbd1fad068520">{"x":{"filter":"none","vertical":false,"extensions":["FixedColumns"],"data":[[101,102,103,104,105,106,107,108,109,110],["image_000101","image_000102","image_000103","image_000104","image_000105","image_000106","image_000107","image_000108","image_000109","image_000110"],["50.5","51.0","51.5","52.0","52.5","53.0","53.5","54.0","54.5","55.0"],["22.79","22.70","22.78","22.78","22.78","22.78","12.96","12.97","12.97","12.97"],["20.92","20.86","20.91","20.90","20.90","20.89","10.88","10.89","10.93","10.96"],["-32.15","-32.07","-32.12","-32.12","-32.12","-32.12","-18.87","-18.88","-18.91","-18.93"],["38.36","38.25","38.33","38.33","38.32","38.31","21.78","21.80","21.84","21.87"],["303.06","303.05","303.05","303.05","303.05","303.05","299.97","299.98","300.03","300.06"],["85.98","86.00","85.96","85.96","85.96","85.95","85.95","85.94","85.99","86.01"],["56.81","56.61","56.81","56.80","56.80","56.80","33.45","33.49","33.51","33.55"],["45.30","45.15","45.31","45.30","45.31","45.31","29.46","29.49","29.46","29.46"],["102.73","102.40","102.69","102.68","102.68","102.68","59.68","59.73","59.77","59.81"]],"container":"<table class=\"cell-border stripe\">\n  <thead>\n    <tr>\n      <th>frame<\/th>\n      <th>frame_id<\/th>\n      <th>time<\/th>\n      <th>L<\/th>\n      <th>A<\/th>\n      <th>B<\/th>\n      <th>C<\/th>\n      <th>H<\/th>\n      <th>S<\/th>\n      <th>r<\/th>\n      <th>g<\/th>\n      <th>b<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"dom":"t","scrollX":true,"scrollCollapse":true,"paging":false,"autoWidth":true,"fixedColumns":true,"columnDefs":[{"className":"dt-right","targets":0},{"className":"dt-right","targets":[2,3,4,5,6,7,8,9,10,11]},{"className":"dt-center","targets":1}],"initComplete":"function(settings, json) {\n$(this.api().table().header()).css({'font-size': '12pt'});\n}","order":[],"orderClasses":false,"rowCallback":"function(row, data, displayNum, displayIndex, dataIndex) {\nvar value=data[0]; $(this.api().cell(row, 0).node()).css({'font-size':'10pt'});\nvar value=data[1]; $(this.api().cell(row, 1).node()).css({'font-size':'10pt'});\nvar value=data[2]; $(this.api().cell(row, 2).node()).css({'font-size':'10pt'});\nvar value=data[3]; $(this.api().cell(row, 3).node()).css({'font-size':'10pt'});\nvar value=data[4]; $(this.api().cell(row, 4).node()).css({'font-size':'10pt'});\nvar value=data[5]; $(this.api().cell(row, 5).node()).css({'font-size':'10pt'});\nvar value=data[6]; $(this.api().cell(row, 6).node()).css({'font-size':'10pt'});\nvar value=data[7]; $(this.api().cell(row, 7).node()).css({'font-size':'10pt'});\nvar value=data[8]; $(this.api().cell(row, 8).node()).css({'font-size':'10pt'});\nvar value=data[9]; $(this.api().cell(row, 9).node()).css({'font-size':'10pt'});\nvar value=data[10]; $(this.api().cell(row, 10).node()).css({'font-size':'10pt'});\nvar value=data[11]; $(this.api().cell(row, 11).node()).css({'font-size':'10pt'});\n}"}},"evals":["options.initComplete","options.rowCallback"],"jsHooks":[]}</script><div class="inline-table"><table width="100%" class="table table-sm">
<caption>
<span id="tab:tools-tidyverse-table-tidy">Table 3.1: </span>Colour data for frames fom a film arranged in tidy format. ☝
</caption>
</table></div>
<p>The tidy data approach provides a standard way to think about data is arranged that makes it quicker and easier to process. The need to rearrange the data into other messy formats is reduced (but not eliminated). The different packages in the tidyverse all expect data to be arranged the same way and so it is easier to move through the different stages of data analysis with tidy data. I find that once I have loaded the tidyverse package I use functions from several of the packages in the tidyverse suite together seamlessly, rarely thinking about which specific packages I am using. This reduces the amount of time I need to spend wrangling data so that I can spend more time thinking about the questions of film form and film style we are trying to answer.</p>
</div>
</div>
<div id="the-pipe-operator" class="section level3" number="3.1.6">
<h3>
<span class="header-section-number">3.1.6</span> The pipe operator<a class="anchor" aria-label="anchor" href="#the-pipe-operator"><i class="fas fa-link"></i></a>
</h3>
<p>The pipe operator <code>%&gt;%</code> from the <a href="https://cran.r-project.org/web/packages/magrittr/vignettes/magrittr.html">magrittr</a> and <a href="https://dplyr.tidyverse.org">dplyr</a> packages makes it easy to chain together commands.</p>
<p>Use of the pipe operator makes code easier to read and edit because there is no need for nested function calls. Commands flow left-to-right and top-to-bottom rather than inside-out, while the need for intermediary variables cluttering the workspace and using up memory is reduced (though not eliminated – long chains of piped commands can become unwieldy to troubleshoot). For example, the three code chunks below perform the same operations of (1) taking the <a href="https://r-lang.com/r-exp-function-with-example/">exponent</a> of each value in the vector <code>num</code>, (2) summing the exponents, (3) taking the logarithm of that sum, and (4) then rounding the result to one decimal place and (5) storing the result in the object <code>num_output</code>; but one is logically simpler and more efficient than the others.</p>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Set the seed of R's random number generator for reproducibility</span>
<span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span> 
<span class="co"># Create a vector of 10 random numbers from a uniform distribution</span>
<span class="va">num</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">10</span><span class="op">)</span>

<span class="co"># Example 1: using nested functions</span>
<span class="va">num_output_ex1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="va">num</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>, <span class="fl">1</span><span class="op">)</span>

<span class="va">num_output_ex1</span></code></pre></div>
<pre><code>## [1] 2.9</code></pre>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Example 2: using intermediary variables</span>
<span class="va">num_exponents</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="va">num</span><span class="op">)</span>
<span class="va">num_exponents_sum</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">num_exponents</span><span class="op">)</span>
<span class="va">num_exponents_sum_log</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">num_exponents_sum</span><span class="op">)</span>
<span class="va">num_output_ex2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="va">num_exponents_sum_log</span>, <span class="fl">1</span><span class="op">)</span>

<span class="va">num_output_ex2</span></code></pre></div>
<pre><code>## [1] 2.9</code></pre>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Example 3: using the pipe operator</span>
<span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">dplyr</span><span class="op">)</span> <span class="co"># call the dplyr package to use the pipe operator</span>
<span class="va">num_output_ex3</span> <span class="op">&lt;-</span> <span class="va">num</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">1</span><span class="op">)</span>

<span class="va">num_output_ex3</span></code></pre></div>
<pre><code>## [1] 2.9</code></pre>
<p>R has other pipe operators to perform the same task, but we will only use <code>%&gt;%</code> in this book because it is the operator used most widely.</p>
</div>
<div id="df" class="section level3" number="3.1.7">
<h3>
<span class="header-section-number">3.1.7</span> Data frames<a class="anchor" aria-label="anchor" href="#df"><i class="fas fa-link"></i></a>
</h3>
<p>A <a href="https://en.wikipedia.org/wiki/Data_structure">data structure</a> is a way of storing information in a computer. R has many different types of data structures, but the data structure we will use extensively throughout this book is the <a href="http://www.r-tutor.com/r-introduction/data-frame">data frame</a>.</p>
<p>A data frame is a two-dimensional data structure – a table – that can store <em>different</em> types of data, including numerical data, logical values (i.e., <code>TRUE</code> and <code>FALSE</code>), or text. Other R data structures, such as a vector or a matrix, can only store a single type of data. This makes data frames a highly flexible data structure.</p>
<p>To get the structure of a data frame we can use dplyr’s <code>glimpse()</code> function. For example, to see the structure of the Early Hitchcock editing data set we will use in chapters <a href="editingI.html#editingI">6</a> and <a href="editingII.html#editingII">7</a>, we load the <code>.csv</code> file containing the shot length data using <code><a href="https://readr.tidyverse.org/reference/read_delim.html">readr::read_csv()</a></code> to create a data frame <code>df_hitchcock</code> and call <code>dplyr::glimpse(df_hitchcock)</code>.</p>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">df_hitchcock</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="st">"Data"</span>, <span class="st">"early_Hitchcock.csv"</span><span class="op">)</span>, show_col_types <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>

<span class="co"># Inspect the data set</span>
<span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">df_hitchcock</span><span class="op">)</span></code></pre></div>
<pre><code>## Rows: 1,056
## Columns: 9
## $ `The Ring (1927)`         &lt;dbl&gt; 4.04, 8.46, 5.58, 6.00, 1.71, 5.04, 5.13, 1.~
## $ `The Farmers Wife (1928)` &lt;dbl&gt; 5.79, 17.13, 8.67, 5.08, 4.50, 11.08, 2.75, ~
## $ `Champagne (1928)`        &lt;dbl&gt; 19.21, 16.96, 3.42, 14.71, 2.67, 2.79, 1.58,~
## $ `The Manxman (1929)`      &lt;dbl&gt; 7.8, 25.1, 7.5, 3.1, 3.2, 2.2, 2.0, 8.4, 7.6~
## $ `Blackmail (1929)`        &lt;dbl&gt; 6.88, 4.67, 2.96, 1.75, 2.67, 6.21, 7.25, 5.~
## $ `Murder (1930)`           &lt;dbl&gt; 6.0, 2.9, 2.3, 1.4, 36.0, 4.5, 6.4, 3.1, 19.~
## $ `The Skin Game (1931)`    &lt;dbl&gt; 19.38, 5.71, 105.17, 1.40, 3.00, 9.30, 2.80,~
## $ `Rich and Strange (1931)` &lt;dbl&gt; 36.9, 9.3, 3.8, 4.4, 2.5, 2.3, 2.0, 3.4, 7.0~
## $ `Number Seventeen (1932)` &lt;dbl&gt; 43.8, 3.3, 77.7, 7.5, 4.5, 3.4, 4.0, 2.4, 8.~</code></pre>
<p>The output tells us that the object <code>df_hitchcock</code> has 1056 rows and 9 columns. Then we get a list of the columns in the data set listing their names, indicating their type as <code>&lt;dbl&gt;</code> (which is short for <a href="https://en.wikipedia.org/wiki/Double-precision_floating-point_format%20and%20is%20used%20to%20represent%20numbers%20with%20decimal%20points">double-precision floating-point format</a>), and showing the first few values in each column of the data frame. The <code><a href="https://rdrr.io/r/utils/head.html">head()</a></code> function also let’s us see the top few rows of the <code>df_hitchcock</code> data frame, which makes it easy to grasp the structure of a data frame in the tidy format.</p>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">df_hitchcock</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 9
##   The Ring (19~1 The F~2 Champ~3 The M~4 Black~5 Murde~6 The S~7 Rich ~8 Numbe~9
##            &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1           4.04    5.79   19.2      7.8    6.88     6     19.4     36.9    43.8
## 2           8.46   17.1    17.0     25.1    4.67     2.9    5.71     9.3     3.3
## 3           5.58    8.67    3.42     7.5    2.96     2.3  105.       3.8    77.7
## 4           6       5.08   14.7      3.1    1.75     1.4    1.4      4.4     7.5
## 5           1.71    4.5     2.67     3.2    2.67    36      3        2.5     4.5
## 6           5.04   11.1     2.79     2.2    6.21     4.5    9.3      2.3     3.4
## # ... with abbreviated variable names 1: `The Ring (1927)`,
## #   2: `The Farmers Wife (1928)`, 3: `Champagne (1928)`,
## #   4: `The Manxman (1929)`, 5: `Blackmail (1929)`, 6: `Murder (1930)`,
## #   7: `The Skin Game (1931)`, 8: `Rich and Strange (1931)`,
## #   9: `Number Seventeen (1932)`</code></pre>
<p>We can access the individual columns of a data frame using the <code>$</code> operator. To see the first few rows of the <code>Blackmail (1929)</code> column only in the <code>df_hitchcock</code> data frame, we use <code>head(df_hitchcock$`Blackmail (1929)`)</code>. Note that we need backticks (<code>`</code>) around the column name because it includes a space.</p>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">df_hitchcock</span><span class="op">$</span><span class="va">`Blackmail (1929)`</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 6.88 4.67 2.96 1.75 2.67 6.21</code></pre>
<p>The columns in a data frame <em>must</em> have equal numbers of rows and so R will populate any empty cells with <code>NA</code> to ensure that all columns are the same length. We can get a complete summary of a data frame using the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> function. For columns storing numeric data, this will return a summary of each column in a data frame including the <a href="https://en.wikipedia.org/wiki/Five-number_summary">five-number summary</a>, the mean value, and the number of <code>NA</code> values in a column.</p>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">df_hitchcock</span><span class="op">)</span></code></pre></div>
<pre><code>##  The Ring (1927)  The Farmers Wife (1928) Champagne (1928) The Manxman (1929)
##  Min.   : 0.040   Min.   : 0.250          Min.   : 0.040   Min.   : 0.600    
##  1st Qu.: 2.170   1st Qu.: 2.290          1st Qu.: 2.290   1st Qu.: 2.600    
##  Median : 3.520   Median : 4.000          Median : 4.040   Median : 4.400    
##  Mean   : 5.006   Mean   : 5.746          Mean   : 5.883   Mean   : 6.074    
##  3rd Qu.: 6.140   3rd Qu.: 6.900          3rd Qu.: 7.330   3rd Qu.: 7.525    
##  Max.   :57.630   Max.   :78.830          Max.   :63.710   Max.   :52.500    
##                   NA's   :49              NA's   :163      NA's   :248       
##  Blackmail (1929) Murder (1930)    The Skin Game (1931) Rich and Strange (1931)
##  Min.   :  0.92   Min.   :  0.50   Min.   :  0.80       Min.   : 0.200         
##  1st Qu.:  2.88   1st Qu.:  2.10   1st Qu.:  2.20       1st Qu.: 2.000         
##  Median :  5.42   Median :  4.80   Median :  5.10       Median : 3.700         
##  Mean   : 11.47   Mean   : 13.73   Mean   : 18.05       Mean   : 7.111         
##  3rd Qu.: 12.75   3rd Qu.: 15.32   3rd Qu.: 14.20       3rd Qu.: 7.100         
##  Max.   :148.17   Max.   :223.90   Max.   :281.00       Max.   :79.100         
##  NA's   :618      NA's   :618      NA's   :787          NA's   :369            
##  Number Seventeen (1932)
##  Min.   : 0.100         
##  1st Qu.: 1.300         
##  Median : 2.400         
##  Mean   : 5.658         
##  3rd Qu.: 5.350         
##  Max.   :77.700         
##  NA's   :401</code></pre>
<p><code>NA</code> values will need to be removed before using the data in a column using the <code><a href="https://rdrr.io/r/stats/na.fail.html">na.omit()</a></code> function. Applying this process to the shot length data for <em>Blackmail</em> (1929), we see that the <code>Blackmail (1929)</code> column in the <code>df_hitchcock</code> data frame has 1056 values. However, we see from the above summary that 618 of these are <code>NA</code> values. After omitting the <code>NA</code> values we see that there are actually 438 shots in the film for which we have data.</p>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Check the length of the column storing the Blackmail </span>
<span class="co"># shot length data in the df_hitchcock data frame</span>
<span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">df_hitchcock</span><span class="op">$</span><span class="va">`Blackmail (1929)`</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 1056</code></pre>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Create a new object storing the Blackmail shot length </span>
<span class="co"># data having removed NA values</span>
<span class="va">blackmail</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/na.fail.html">na.omit</a></span><span class="op">(</span><span class="va">df_hitchcock</span><span class="op">$</span><span class="va">`Blackmail (1929)`</span><span class="op">)</span>

<span class="co"># Check the length of the new object blackmail</span>
<span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">blackmail</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 438</code></pre>
<p>We will designate data frames in the workspace with the prefix <code>df_</code> so that we are always aware what type of object we are working with. We will occasionally use other data structures, such as a matrix, but whenever possible we will ensure our data is structured as a data frame that is as tidy as possible.</p>
</div>
</div>
<div id="rstudio" class="section level2" number="3.2">
<h2>
<span class="header-section-number">3.2</span> RStudio<a class="anchor" aria-label="anchor" href="#rstudio"><i class="fas fa-link"></i></a>
</h2>
<p>RStudio is a cross-platform <a href="https://en.wikipedia.org/wiki/Integrated_development_environment">integrated development environment</a> (IDE) that is more user‑friendly than the base R console, though it is not necessary to install an IDE to use R. The installer for RStudio can be downloaded at <a href="https://www.rstudio.com/products/rstudio/download/">https://www.rstudio.com/products/rstudio/download/</a>. RStudio Cloud makes a browser-based version of the IDE available though in this book I will assume you are using the desktop version.</p>
<p>Using RStudio means that many of the tasks we encounter using R can be automated to save time. For example, rather than type out the assignment operator <code>&lt;-</code> every time we can use the keyboard shortcut <kbd>ALT</kbd> + <kbd>-</kbd>. We can set RStudio to save an <code>.RData</code> file of the workspace on exiting the IDE and to load that file on start-up if we wish to do so. RStudio also features <a href="https://support.rstudio.com/hc/en-us/articles/205273297-Code-Completion-in-the-RStudio-IDE"><em>code completion</em></a> for packages, functions and arguments, and objects in the workspace to speed up the process or writing code and reduce the potential for errors arising through typos; <a href="https://en.wikipedia.org/wiki/Syntax_highlighting"><em>syntax highlighting</em></a> to more easily distinguish between functions, strings, values, and other objects; and <a href="https://en.wikipedia.org/wiki/Bracket_matching"><em>bracket matching</em></a> to save time when writing and troubleshooting code.</p>
<div id="the-rstudio-interface" class="section level3" number="3.2.1">
<h3>
<span class="header-section-number">3.2.1</span> The RStudio interface<a class="anchor" aria-label="anchor" href="#the-rstudio-interface"><i class="fas fa-link"></i></a>
</h3>
<p>Opening the RStudio interface presents us with a set of panes, some of which contain a set of tabs to access specific information in an R session.</p>
<ul>
<li>The <em>Console</em> pane contains the standard R console, where code is entered and run, and where the results are returned.</li>
<li>The <em>Files</em> pane contains tabs that let you explore files in the current working directory and navigate to other directories on your computer (Files); display and export plots (Plots); see which packages are available and currently loaded into the workspace (Packages); and access help on R in general, specific packages, or functions (Help).</li>
<li>The <em>Environment</em> pane contains tabs that let you see what objects are in the workspace in the current R session (Environment); and see the history of commands that have been sent to R (History).</li>
<li>The <em>Source</em> pane lets you inspect objects in the workspace (data frames, lists, etc.) and to write code in scripts.</li>
</ul>
<p>In the console, a line of code is evaluated interactively when we presses <kbd>Enter</kbd>. This is fine for single lines of code to be executed immediately but is cumbersome if we have a longer piece of code that requires several steps to be executed in sequence. It is therefore preferable to write code as a script in the Source pane, where a single command can run across multiple lines and/or a series of commands can be written and run together. A new script file can be created using <code>File &gt; New File &gt; R Script</code> or using the shortcut <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>N</kbd>. Unlike the console, pressing <kbd>Enter</kbd> does not cause a line of code to be evaluated; it adds a new line to the script. To run a chunk of code in a script, highlight the desired lines (for single lines of code placing the cursor at the beginning or end of the line is sufficient) and press <kbd>Ctrl</kbd> + <kbd>Enter</kbd>. To run all the code in a script, press <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Enter</kbd>. Running the code from a script sends it to the console to be evaluated, where the results will also be returned. A script can be saved using <code>File &gt; Save As…</code> and naming the script with the <code>.R</code> extension.</p>
<p>Opening the Global Options menu (<code>Tools &gt; Global Options…</code>) lets the us customize the appearance of RStudio to suit their preferences. See Figure <a href="tools.html#fig:tools-rstudio-image-layout">3.2</a> for my customised layout for RStudio.</p>
<ul>
<li>On the Pane Layout page, we can change the location of the panes in the interface to suit their preference and to assign tabs to panes. For example, I have moved the Files tab to the same pane as the Environment tab for my customisation of RStudio.</li>
<li>The Appearance page lets us select the RStudio theme, editor font and font size, and the editor theme (background colour and syntax highlighting) to suit their needs and preferences.</li>
</ul>
<p>A particularly useful feature available in RStudio is the use of Rainbow parentheses to make it easier to match up parentheses, brackets, and braces when writing code. Mismatching or missing out brackets is a common source of errors when coding but by turning on Rainbow parentheses the colour coding of items in a script makes it easier to spot where errors occur. To turn on Rainbow parentheses open the <code>Global options</code> dialogue box from the <code>Tools</code> menu and select <code>Code</code> followed by <code>Display</code>. Check the <code>Rainbow parentheses</code> box. Note that this will only work when coding a script in the source window. It does <em>not</em> apply when coding in the console, where text will <em>always</em> be monochrome. This is another reason to write R scripts in the Source pane rather than the console.</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:tools-rstudio-image-layout"></span>
<img src="Images/tools-rstudio-image-layout.png" alt="My customised layout of the RStudio interface. Text in the Source pane (top left) is highlighted using a customised version of the Monokai editor theme and uses rainbow parentheses. Text in the Console (bottom left) is monochrome. The Environment pane (top right) lists the objects currently in the workspace. The Plots pane (bottom right) displays the visualisations I am creating for this book.  ☝️" width="90%" class="zooom"><p class="caption">
Figure 3.2: My customised layout of the RStudio interface. Text in the Source pane (top left) is highlighted using a customised version of the Monokai editor theme and uses rainbow parentheses. Text in the Console (bottom left) is monochrome. The Environment pane (top right) lists the objects currently in the workspace. The Plots pane (bottom right) displays the visualisations I am creating for this book. ☝️
</p>
</div>
</div>
<div id="projects" class="section level3" number="3.2.2">
<h3>
<span class="header-section-number">3.2.2</span> Projects<a class="anchor" aria-label="anchor" href="#projects"><i class="fas fa-link"></i></a>
</h3>
<p>A key advantage of using RStudio is that it simplifies the process of managing projects.</p>
<p>The <em>working directory</em> is the folder where R looks for data to import and scripts to source, and is the destination for any outputs created. A widespread practice is to set the working directory with an absolute path explicitly at the head of a script using the <code><a href="https://rdrr.io/r/base/getwd.html">setwd()</a></code> function.</p>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/getwd.html">setwd</a></span><span class="op">(</span><span class="st">"C:/Users/Nick/Documents"</span><span class="op">)</span></code></pre></div>
<p>This is <em>not</em> advisable. Setting the working directory in this way makes code easy to break and hard to share. An absolute path to a working directory works only as long the directory structure of the computer running the script does not change. If the script file containing the code is moved, the directory structure changes over time, or if code is shared to be run on a different machine, then the path to the working directory is no longer valid. Every <code><a href="https://rdrr.io/r/base/getwd.html">setwd()</a></code> command in every script in a project must be changed to make new valid paths to the working directory, which is tedious and unnecessary.</p>
<p>A better approach is to employ a robust workflow using projects in RStudio and the here package.</p>
<p>By starting a new project in RStudio (<code>File &gt; New Project…</code>) the working directory for that project is set to the project folder, which can be created when starting a new project in RStudio or associated with an existing folder. An <code>.Rproj</code> file, which stores the settings for that project, is linked to the project folder. Opening an existing project in RStudio (<code>File &gt; Open Project</code>) starts a new R session and automatically sets the working directory for that session to the project folder and loads any <code>.RData</code> and <code>.RHistory</code> files, plus any other project settings.</p>
<p>Once the project folder has been created and associated with an <code>.Rproj</code> file, it is time to create the folders that will organise the source data for analysis, the scripts that contain the code we create, and the outputs produced. The organisation of an R project depends on the nature of the research project, but Figure <a href="tools.html#fig:tools-projects-image-folders">3.3</a> illustrates a basic folder structure for an R project as a starting point for thinking about projects. The <code>.Rproj</code> file is at the top level of the project so that the working directory is set to the project folder and all paths to folders and files within the project are <em>relative</em> to the project folder. Using paths relative to the project folder means that code will work even if the location of the project folder changes.</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:tools-projects-image-folders"></span>
<img src="Images/tools-projects-image-folders.png" alt="A basic structure for an R project." width="90%"><p class="caption">
Figure 3.3: A basic structure for an R project.
</p>
</div>
<div id="here" class="section level4" number="3.2.2.1">
<h4>
<span class="header-section-number">3.2.2.1</span> here<a class="anchor" aria-label="anchor" href="#here"><i class="fas fa-link"></i></a>
</h4>
<p>The <a href="https://here.r-lib.org/index.html">here</a> package makes working with relative paths easy to manage. <code><a href="https://here.r-lib.org//reference/here.html">here::here()</a></code> gets the file path to the project folder of the current project (which it determines by the presence of the <code>.Rproj</code> file) and lets us create paths relative to that folder. For example, to read a <code>.csv</code> file from the Data folder in the project folder we wrap the file information in a <code>here()</code> command within the call to read the file (<code><a href="https://readr.tidyverse.org/reference/read_delim.html">readr::read_csv()</a></code>) and list the folders within the project folder (“Data”) and the files (“data.csv”) in order.</p>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Install the tidyverse (which includes the readr package) and </span>
<span class="co"># here packages if you have not already done so</span>
<span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">here</span>, <span class="va">tidyverse</span><span class="op">)</span>

<span class="va">df</span> <span class="op">&lt;-</span> <span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="st">"Data"</span>, <span class="st">"data.csv"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>Similarly, to write a data frame to a <code>.csv</code> file in the <code>Outputs &gt; Data</code> folder we build a path by listing the folders and file name in order.</p>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">readr</span><span class="fu">::</span><span class="fu"><a href="https://readr.tidyverse.org/reference/write_delim.html">write_csv</a></span><span class="op">(</span><span class="va">df</span>, <span class="fu">here</span><span class="fu">::</span><span class="fu"><a href="https://here.r-lib.org//reference/here.html">here</a></span><span class="op">(</span><span class="st">"Outputs"</span>, <span class="st">"Data"</span>, <span class="st">"data_output.csv"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>An advantage of using the here package is that we no longer need to worry about how to enter paths on different platforms. On MacOs and Linux, paths are written using single forward slashes to separate folders (<kbd>/</kbd>), while on Windows machines paths to files use single backlashes (e.g., <code>C:\Users\Nick\Documents</code>). However, because backslashes are used to escape characters in strings, R will not recognise the path on a Windows machine as a path and so it is necessary to edit the location of a folder to use either double backslashes (<code>C:\\Users\\Nick\\Documents</code>) or single forward slashes (<code>C:/Users/Nick/Documents</code>). This is tedious and another way in which code can be broken. This problem is easily eliminated by using the here package, which does not require us to enter back- or forward slashes.</p>
</div>
<div id="a-script-for-the-folder-structure-of-a-project" class="section level4" number="3.2.2.2">
<h4>
<span class="header-section-number">3.2.2.2</span> A script for the folder structure of a project<a class="anchor" aria-label="anchor" href="#a-script-for-the-folder-structure-of-a-project"><i class="fas fa-link"></i></a>
</h4>
<p>Once we have created our project folder and associated it with an <code>.Rproj</code> file we can create a function called <code>project_folders()</code> using the here package and the <code><a href="https://rdrr.io/r/base/files2.html">dir.create()</a></code> function that will create the basic folder structure we need for a project.</p>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">project_folders</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="op">)</span><span class="op">{</span>  <span class="co"># no arguments are required</span>
  
  <span class="co"># Load the here package</span>
  <span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">here</span><span class="op">)</span>
  
  <span class="co"># Name the folders and sub-folders for the project</span>
  <span class="va">folders</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Data"</span>, <span class="st">"Scripts"</span>, <span class="st">"Outputs"</span><span class="op">)</span>
  <span class="va">Outputs_sub_folders</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Data"</span>, <span class="st">"Plots"</span><span class="op">)</span>
  
  <span class="co"># Loop over the folders to create them in the project directory</span>
  <span class="kw">for</span> <span class="op">(</span><span class="va">f</span> <span class="kw">in</span> <span class="va">folders</span><span class="op">)</span><span class="op">{</span><span class="fu"><a href="https://rdrr.io/r/base/files2.html">dir.create</a></span><span class="op">(</span><span class="va">f</span><span class="op">)</span><span class="op">}</span>
  
  <span class="co"># Loop over the sub-folders to create them in the Outputs directory</span>
  <span class="kw">for</span> <span class="op">(</span><span class="va">s</span> <span class="kw">in</span> <span class="va">Outputs_sub_folders</span><span class="op">)</span><span class="op">{</span><span class="fu"><a href="https://rdrr.io/r/base/files2.html">dir.create</a></span><span class="op">(</span><span class="fu">here</span><span class="op">(</span><span class="st">"Outputs"</span>, <span class="va">s</span><span class="op">)</span><span class="op">)</span><span class="op">}</span>
  
<span class="op">}</span>

<span class="co"># To run the function</span>
<span class="fu">project_folders</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p>A <code>for</code> loop repeats a specific piece of code a set number of times, iterating over the values in a sequence. For example, in the above code the function <code><a href="https://rdrr.io/r/base/files2.html">dir.create()</a></code> is applied once for every item (<code>f</code>) in the list <code>folders</code>. Using the here package we can specify in which folder the sub-folders will be created and run another loop to create sub-folders within the Outputs directory. <code>for</code> loops save time by removing the need to repeatedly execute the same piece of code but they are often one of the slowest ways of executing code in R. However, in this book we will use <code>for</code> loops so we can see what the code we are using does at each step – our aim is understanding rather than speed. Once you feel you understand the code, you can experiment with putting the content of a loop into a function and then using R’s <a href="https://www.learnbyexample.org/r-apply-functions/">family of apply functions</a>, such as <code><a href="https://rdrr.io/r/base/lapply.html">lapply()</a></code> and <code><a href="https://rdrr.io/r/base/lapply.html">sapply()</a></code>, to run code efficiently.</p>
<p>We can save the <code>project_folders()</code> function as a script – let’s call it <code>project_folders.R</code> – that we can source and run at the beginning a new project. Make sure you make a note of where you save this script, as creating the folder structure will be one of the first tasks in every chapter in this book: we simply copy the script to the project folder, source the function using <code>source("project_folders.R")</code> and run the function.</p>
</div>
</div>
<div id="accessing-help" class="section level3" number="3.2.3">
<h3>
<span class="header-section-number">3.2.3</span> Accessing help<a class="anchor" aria-label="anchor" href="#accessing-help"><i class="fas fa-link"></i></a>
</h3>
<p>Help on packages and functions can be accessed directly within RStudio. Vignettes describing packages and illustrating how to use their functions can be accessed using <code><a href="https://rdrr.io/r/utils/browseVignettes.html">browseVignettes()</a></code>. For example, to see the vignettes for the seewave package we use</p>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/browseVignettes.html">browseVignettes</a></span><span class="op">(</span>package <span class="op">=</span> <span class="st">"seewave"</span><span class="op">)</span></code></pre></div>
<p>This will open a list of vignettes in a web browser (NB: an internet connection is required). Not all R packages have vignettes, though many do. To get <code>help</code> with a function from any package currently loaded in the workspace, type help followed by the name of the function in parentheses. For example, to get help with the <code>spectro()</code> function in the seewave package use . This will open the documentation for that function in the help tab of RStudio.</p>
<p>RStudio also has a Tutorial tab for learning about how to use R and which requires the <a href="https://rstudio.github.io/learnr/">learnr</a> package.</p>
</div>
</div>
<div id="ffmpeg" class="section level2" number="3.3">
<h2>
<span class="header-section-number">3.3</span> FFmpeg<a class="anchor" aria-label="anchor" href="#ffmpeg"><i class="fas fa-link"></i></a>
</h2>
<p>To process audio and video we will need FFmpeg, a free command-line based utility for decoding, encoding, and converting media files that is the workhorse of several packages across different languages for media processing. FFmpeg can be used to encode/decode/transcode and mux/demux multimedia files. It can be used for blurring and denoising, colour conversion, letterboxing, extracting individual frames, and adding or removing subtitles from video files.</p>
<p>On MacOS, FFmpeg is easily installed as a package from <a href="https://formulae.brew.sh/formula/ffmpeg#default">Homebrew</a>. On Linux it can be installed via a package manager. FFmpeg does not require installation on Windows, but it is necessary to set an environment path to FFmpeg so that commands addressed to it are executed.</p>
<hr>
<details><summary style="font-size:16px; font-weight: bold;">
👈 Click here to learn how to set FFmpeg as an environment variable in Windows
</summary><div class="rmdimportant">
<h3 style="margin-top: -5px;">
Setting FFmpeg as an environment variable in Windows
</h3>
<p>
The following steps will allow you to download FFmpeg and set it as
an environment variable in the operating system.
</p>
<ol style="list-style-type: decimal">
<li>
Go to <a href="https://ffmpeg.org/download.html">https://ffmpeg.org/download.html</a>
and select the Windows logo to get a list of download options for
Windows. Click on <strong>Windows builds from gyan.dev</strong> to go to
the Codex FFmpeg repository.
</li>
<li>
Select the latest <em>full</em> build:
<code>ffmpeg-git-full.7z</code>. This will begin downloading FFmpeg as a
compressed zip file to your default <strong>Downloads</strong>
folder.
</li>
<li>
Open your default <strong>Downloads</strong> folder, right-click on
the file you have just downloaded and select <strong>Extract
here</strong>. This will unpack the compressed file to a new folder.
Rename this folder <strong>FFmpeg</strong>.
</li>
<li>
Cut-and-paste this folder from your <strong>Downloads</strong>
folder to the root directory of your PC (C:\).
</li>
<li>
Open the Windows search box (<kbd>Windows</kbd> + <kbd>s</kbd>) and
type <strong>Environment variables</strong> into the search box.
Select<strong>Edit the system environment variables</strong> to open the
<strong>System Properties</strong> dialogue box.
</li>
<li>
In the <strong>System Properties</strong> dialogue box click the
<strong>Environment variables…</strong> button in the bottom right-hand
corner to open the <strong>Environment variables</strong> dialogue
box.
</li>
<li>
In the <strong>User variables for &lt;username&gt;</strong> panel,
select <strong>Path</strong> and click <strong>Edit</strong>.
</li>
<li>
Click <strong>New</strong> and type <code>C:\FFmpeg\bin</code> at
the prompt. Click <strong>OK</strong> to set the path.
</li>
<li>
Click <strong>OK</strong> in the <strong>Environment
variables</strong> dialogue box to save your changes. Click
<strong>OK</strong> to exit the <strong>System Properties</strong>
dialogue box.
</li>
</ol>
<p>
FFmpeg should now be set as a environment variable in Windows. To
check this, open the Windows search box (<kbd>Windows</kbd> +
<kbd>s</kbd>), type <strong>PowerShell</strong>, and select
<strong>Windows PowerShell</strong> from the results. Once the window
has opened, enter <code>ffmpeg</code> at the prompt and press
<kbd>Enter</kbd>. If FFmpeg has been set as an environment variable
correctly PowerShell will display a summary of the version of FFmpeg you
have now set up on your PC.
</p>
</div>
</details><hr>
<p>FFmpeg can be used via the <a href="https://en.wikipedia.org/wiki/Command-line_interface">command line</a> or it can be called by passing system commands from R to the operating system. To streamline our workflow, we will work within a single environment and enter FFmpeg commands via R using the av package to simplify code when possible. For example, to convert a <code>.webm</code> file to an <code>.mp4</code> file without re-encoding the data using FFmpeg within R we pass the following command to the system:</p>
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/system.html">system</a></span><span class="op">(</span><span class="st">"ffmpeg -i input_video.webm output_video.mp4"</span><span class="op">)</span></code></pre></div>
<p>Breaking this down:</p>
<ul>
<li>the <code><a href="https://rdrr.io/r/base/system.html">system()</a></code> function passes a command to the OS as a string – note the use of quote marks around the command.</li>
<li>
<code>ffmpeg</code>: tells the OS we are entering a command for FFmpeg</li>
<li>
<code>-i input_video.webm</code>: <code>-i</code> indicates this is an input command and is followed by the exact name of the video file to be converted</li>
<li>
<code>output_video.mp4</code>: sets the name of the output file. The name of the output can be prefaced with <code>-vcodec libx264</code> to control the encoding of the output file.</li>
</ul>
<p>This process can be simplified using the av package for R, which provides an R wrapper for common FFmpeg operations. To convert a .webm file to .mp4 using <code><a href="https://docs.ropensci.org/av/reference/encoding.html">av::av_video_convert()</a></code>, we enter</p>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Load the av package</span>
<span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span><span class="va">av</span><span class="op">)</span>

<span class="fu">av</span><span class="fu">::</span><span class="fu"><a href="https://docs.ropensci.org/av/reference/encoding.html">av_video_convert</a></span><span class="op">(</span><span class="st">"input_video.webm"</span>, output <span class="op">=</span> <span class="st">"output_video.mp4"</span><span class="op">)</span></code></pre></div>
<p>This command performs the exact same conversion as the FFmpeg code at the command line but is more readable.</p>
<div class="rmdtip">
<p>
<em>Programming Historian</em> has a <a href="https://doi.org/10.46430/phen0077">comprehensive guide</a> <span class="citation"><span class="citation">(<a href="references.html#ref-rodriguez2018itat" role="doc-biblioref">Rodriguez, 2018</a>)</span></span> to using FFmpeg for those
who would like to learn more.
</p>
</div>
</div>
<div id="summary-1" class="section level2" number="3.4">
<h2>
<span class="header-section-number">3.4</span> Summary<a class="anchor" aria-label="anchor" href="#summary-1"><i class="fas fa-link"></i></a>
</h2>
<p>The analytical and presentational tools required for a computational film analysis project will vary according to the demands of that project. R is an excellent choice because it can be used with many different types of data and in subsequent chapters we will use R to analyse sound, colour, editing, shot data, and textual data, working directly with audio files, images, and subtitiles, or <code>.csv</code> files containing numerical data derived from films.</p>

</div>
</div>
<script>
// Get the modal
const modal = document.getElementById('myModal');
const modalImg = document.getElementById("img01");
const captionText = document.getElementById("caption");

var img = document.querySelectorAll('.zooom');
    
for (var i=0; i<img.length; i++){
    
    img[i].onclick = function(){
    modal.style.display = "block";
    modalImg.src = this.src;
    modalImg.alt = this.alt;
    captionText.innerHTML = this.alt;
};
     
}

// When the user clicks on <span> (x), close the modal
modal.onclick = function() {
    img01.className += " out";
    setTimeout(function() {
       modal.style.display = "none";
       img01.className = "modal-content";
     }, 400);
    
 };
 </script><div class="chapter-nav">
<div class="prev"><a href="CFA.html"><span class="header-section-number">2</span> Computational film analysis</a></div>
<div class="next"><a href="audio.html"><span class="header-section-number">4</span> Analysing film audio</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#tools"><span class="header-section-number">3</span> Tools</a></li>
<li>
<a class="nav-link" href="#r"><span class="header-section-number">3.1</span> R</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#installing-r"><span class="header-section-number">3.1.1</span> Installing R</a></li>
<li><a class="nav-link" href="#using-r"><span class="header-section-number">3.1.2</span> Using R</a></li>
<li><a class="nav-link" href="#comments"><span class="header-section-number">3.1.3</span> Comments</a></li>
<li><a class="nav-link" href="#functions"><span class="header-section-number">3.1.4</span> Functions</a></li>
<li><a class="nav-link" href="#packages"><span class="header-section-number">3.1.5</span> Packages</a></li>
<li><a class="nav-link" href="#the-pipe-operator"><span class="header-section-number">3.1.6</span> The pipe operator</a></li>
<li><a class="nav-link" href="#df"><span class="header-section-number">3.1.7</span> Data frames</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#rstudio"><span class="header-section-number">3.2</span> RStudio</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#the-rstudio-interface"><span class="header-section-number">3.2.1</span> The RStudio interface</a></li>
<li><a class="nav-link" href="#projects"><span class="header-section-number">3.2.2</span> Projects</a></li>
<li><a class="nav-link" href="#accessing-help"><span class="header-section-number">3.2.3</span> Accessing help</a></li>
</ul>
</li>
<li><a class="nav-link" href="#ffmpeg"><span class="header-section-number">3.3</span> FFmpeg</a></li>
<li><a class="nav-link" href="#summary-1"><span class="header-section-number">3.4</span> Summary</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/DrNickRedfern/CFA-with-R/blob/main/03-Tools.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/DrNickRedfern/CFA-with-R/edit/main/03-Tools.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Computational Film Analysis with R</strong>" was written by Nick Redfern. It was last built on 13 September 2022.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
